

Drop table DOMAIN_SYSTEM_INFORMATION;

create table DOMAIN_SYSTEM_INFORMATION(
    ROW_ID number(10),
    IP_ADDRESS varchar2(20),
    SERVER_NAME varchar2(100),
    OS_VERSION varchar2(100),
    STATUS    varchar2(100)
);


Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (1,'123.123.123.123','SEVER_NAME1','Windows Server 2008','Good');


Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (2,'321.321.123.123','SEVER_NAME2','Windows Server 2008','Ping Failure-Unable to connect');
Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (3,'123.123.123.123','SEVER_NAME3','Windows Server 2012','CPU utiliztion is high');
Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (4,'123.123.123.100','SEVER_NAME4','Windows Server 2008','Physical Memory Utilization is high');

Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (5,'321.321.123.101','SEVER_NAME5','Windows Server 2008','Good');
Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (6,'123.123.123.102','SEVER_NAME6','Windows Server 2012','Shutdown');
Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (7,'123.123.123.103','SEVER7','Windows Server 2008','Accidently Rebooted');


Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (8,'321.321.123.110','SEVER_NAME8','Windows Server 2008','Netowrk Latency Observed');
Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (9,'123.123.123.121','SEVER_NAME9','Windows Server 2012','A Disk Drive went Offline');
Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (10,'123.123.123.123','SEVER_NAME10','Windows Server 2008','Hung Status');


Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (11,'321.321.123.110','SEVER_NAME11','Windows Server 2008','Netowrk Latency Observed');
Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (12,'123.123.123.121','SEVER_NAME12','Windows Server 2012','A Disk Drive went Offline');
Insert into DOMAIN_SYSTEM_INFORMATION( ROW_ID,IP_ADDRESS,SERVER_NAME,OS_VERSION,STATUS) values (13,'123.123.123.123','SEVER_NAME13','Windows Server 2008','Hung Status');

update DOMAIN_SYSTEM_INFORMATION set SERVER_NAME= 'SEVER_NAME7' where ROW_ID = 7;


update DOMAIN_SYSTEM_INFORMATION set SERVER_NAME= 'SEVER_NAME7' where ROW_ID = 7;


select * from DOMAIN_SYSTEM_INFORMATION;

    